[workspace]
description = "Mojo libcurl bindings"
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = [
    "conda-forge",
    "https://conda.modular.com/max",
]
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
license = "MIT"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/thatstoasty/mojo-curl"
repository = "https://github.com/thatstoasty/mojo-curl"
preview = ["pixi-build"]

[feature.util.tasks]
tests = "sh -c 'find test -name \"test_*.mojo\" -exec mojo -D ASSERT=all -I . {} \\;'"
examples = "sh -c 'find examples -name \"*.mojo\" -exec mojo -D ASSERT=all -I . {} \\;'"

# Linting and Formatting
lint_docs = "mojo doc --Werror --diagnose-missing-doc-strings -o /dev/null ./mojo_curl"
mojo_format = "mojo format mojo_curl --line-length 120"
sort_imports = "isort **/*.mojo -m 3 --line-length 120 --lines-after-imports 2 --trailing-comma"
format = [{ task = "mojo_format" }, { task = "sort_imports" }]

# Build and publish
build = { cmd = "pixi build -o ." }
publish = { cmd = "find . -name 'mojo-curl-*.conda' | xargs pixi upload https://prefix.dev/api/v1/upload/mojo-community" }
build_and_publish = [{ task = "build" }, { task = "publish" }]

[package]
name = "mojo-curl"
version = "26.1.1"

[package.build]
backend = { name = "pixi-build-mojo", version = "*" }

[dependencies]
mojo = ">=0.26.1.0,<0.26.2.0"
curl_wrapper = { git = "https://github.com/thatstoasty/mojo-curl.git", subdirectory = "shim", branch = "main" }

[package.build-dependencies]
mojo-compiler = ">=0.26.1.0,<0.26.2.0"

[package.host-dependencies]
mojo-compiler = ">=0.26.1.0,<0.26.2.0"
libcurl = ">=8.17.0,<9.0.0"
curl_wrapper = { path = "shim" }

[package.run-dependencies]
mojo-compiler = ">=0.26.1.0,<0.26.2.0"
libcurl = ">=8.17.0,<9.0.0"
curl_wrapper = { path = "shim" }

[feature.util.dependencies]
isort = ">=6.0.1,<7"

[environments]
default = { solve-group = "default" }
util = { features = ["util"], solve-group = "default" }
