[workspace]
description = "Mojo libcurl bindings"
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = [
    "conda-forge",
    "https://conda.modular.com/max",
]
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
license = "MIT"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/thatstoasty/mojo-curl"
repository = "https://github.com/thatstoasty/mojo-curl"
preview = ["pixi-build"]

[feature.util.tasks]
tests = "mojo scripts/util.mojo tests"
benchmarks = "mojo scripts/util.mojo benchmarks"
examples = "mojo scripts/util.mojo examples"

# Curl wrapper build tasks
build-wrapper = "gcc -shared -fPIC -I$PIXI_PROJECT_ROOT/.pixi/envs/default/include/curl shim/curl_wrapper.c -L$PIXI_PROJECT_ROOT/.pixi/envs/default/lib -lcurl"
clean-wrapper = "rm -f ./libcurl_wrapper.dylib"
test-curl = { depends-on = ["build-wrapper"], cmd = "mojo test.mojo" }

# Linting and Formatting
lint_docs = "python3 scripts/check-docstrings.py"
mojo_format = "mojo format mojo_curl --line-length 120"
sort_imports = "isort **/*.mojo -m 3 --line-length 120 --lines-after-imports 2 --trailing-comma"
format = [{ task = "mojo_format" }, { task = "sort_imports" }]

# Build and publish
build = { cmd = "pixi build -o ." }
publish = { cmd = "find . -name 'mojo-curl-*.conda' | xargs pixi upload https://prefix.dev/api/v1/upload/mojo-community" }
build_and_publish = [{ task = "build" }, { task = "publish" }]

[package]
name = "mojo-curl"
version = "25.7.1"

[package.build.backend]
name = "pixi-build-mojo"
version = "0.*"
channels = ["conda-forge", "https://prefix.dev/pixi-build-backends"]

[dependencies]
mojo = ">=0.25.7.0,<0.26.1.0"
libcurl = ">=8.17.0,<9.0.0"
curl_wrapper = { path = "shim" }

[package.build-dependencies]
mojo-compiler = ">=0.25.7.0,<0.26.1.0"

[package.host-dependencies]
mojo-compiler = ">=0.25.7.0,<0.26.1.0"
libcurl = ">=8.17.0,<9.0.0"
curl_wrapper = { path = "shim" }

[package.run-dependencies]
mojo-compiler = ">=0.25.7.0,<0.26.1.0"
libcurl = ">=8.17.0,<9.0.0"
curl_wrapper = { path = "shim" }

[feature.util.dependencies]
typer = ">=0.16.0,<0.17"
isort = ">=6.0.1,<7"

[environments]
default = { solve-group = "default" }
util = { features = ["util"], solve-group = "default" }
